"use client";

import { useState, useTransition } from "react";
import { Pill } from "@/components/ui/Pill";
import { SentimentBadge } from "@/components/ui/Badge";
import { regenerateSummary, toggleSummaryPin } from "@/lib/actions/digest";
import type { SummariesRow } from "@/types/database";

function formatDate(dateStr: string): string {
  return new Date(`${dateStr}T00:00:00Z`).toLocaleDateString("en-SG", {
    day: "numeric",
    month: "short",
    year: "numeric",
    timeZone: "UTC",
  });
}

function SummaryCard({ summary, showRegenerate }: { summary: SummariesRow; showRegenerate: boolean }) {
  const [expanded, setExpanded] = useState(false);
  const [isPending, startTransition] = useTransition();

  return (
    <div className="rounded-lg border border-white/10 bg-card p-4">
      <div className="flex items-start justify-between gap-3">
        <button type="button" onClick={() => setExpanded((v) => !v)} className="flex-1 text-left">
          <p className="font-semibold text-white">
            {formatDate(summary.period_start)} – {formatDate(summary.period_end)}
          </p>
          <div className="mt-1.5 flex flex-wrap items-center gap-1.5">
            {summary.dominant_sentiment && <SentimentBadge sentiment={summary.dominant_sentiment} />}
            <span className="text-xs text-gray-400">{summary.item_count} items</span>
            {summary.key_themes.map((theme) => (
              <Pill key={theme}>{theme}</Pill>
            ))}
          </div>
        </button>
        <div className="flex shrink-0 items-center gap-3">
          {showRegenerate && (
            <button
              type="button"
              disabled={isPending}
              onClick={() => startTransition(() => regenerateSummary(summary.id))}
              className="text-sm text-gray-500 hover:text-gray-300 disabled:opacity-50"
              title="Regenerate this digest"
            >
              {isPending ? "Regenerating…" : "🔄 Regenerate"}
            </button>
          )}
          <button
            type="button"
            disabled={isPending}
            onClick={() => startTransition(() => toggleSummaryPin(summary.id, summary.is_pinned))}
            className={`text-sm ${summary.is_pinned ? "text-accent" : "text-gray-500 hover:text-gray-300"}`}
            title={summary.is_pinned ? "Unpin" : "Pin"}
          >
            {summary.is_pinned ? "📌 Pinned" : "📌 Pin"}
          </button>
        </div>
      </div>

      <p className="mt-2 text-xs text-gray-500">Generated by AI ({summary.provider_used ?? "unknown"})</p>

      {expanded && (
        <p className="mt-3 whitespace-pre-line border-t border-white/10 pt-3 text-sm leading-relaxed text-gray-200">
          {summary.content}
        </p>
      )}
    </div>
  );
}

/** Section 13.3: groups same-period regenerations together, showing the latest as current and older versions tucked behind a toggle. */
function DigestGroup({ versions }: { versions: SummariesRow[] }) {
  const [showHistory, setShowHistory] = useState(false);
  const [current, ...older] = versions;

  return (
    <div className="space-y-2">
      <SummaryCard summary={current} showRegenerate />
      {older.length > 0 && (
        <div className="pl-2">
          <button
            type="button"
            onClick={() => setShowHistory((v) => !v)}
            className="text-xs text-gray-500 hover:text-gray-300"
          >
            {showHistory ? "Hide" : "Show"} {older.length} earlier version{older.length > 1 ? "s" : ""}
          </button>
          {showHistory && (
            <div className="mt-2 space-y-2">
              {older.map((s) => (
                <SummaryCard key={s.id} summary={s} showRegenerate={false} />
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function groupByPeriod(summaries: SummariesRow[]): SummariesRow[][] {
  const order: string[] = [];
  const map = new Map<string, SummariesRow[]>();
  for (const s of summaries) {
    const key = `${s.period_start}_${s.period_end}`;
    if (!map.has(key)) {
      map.set(key, []);
      order.push(key);
    }
    map.get(key)!.push(s);
  }
  return order.map((key) => map.get(key)!.sort((a, b) => b.generated_at.localeCompare(a.generated_at)));
}

export function DigestClient({
  weekly,
  monthly,
}: {
  weekly: SummariesRow[];
  monthly: SummariesRow[];
}) {
  const [tab, setTab] = useState<"weekly" | "monthly">("weekly");
  const groups = groupByPeriod(tab === "weekly" ? weekly : monthly);
  const emptyLabel =
    tab === "weekly"
      ? "No weekly digest yet. Digests are generated automatically every Monday."
      : "No monthly digest yet. Digests are generated automatically on the 1st of each month.";

  return (
    <div>
      <div className="mb-4 flex gap-2 border-b border-white/10">
        {(["weekly", "monthly"] as const).map((t) => (
          <button
            key={t}
            type="button"
            onClick={() => setTab(t)}
            className={`px-3 py-2 text-sm font-medium capitalize ${
              tab === t ? "border-b-2 border-accent text-white" : "text-gray-400"
            }`}
          >
            {t}
          </button>
        ))}
      </div>

      {groups.length === 0 ? (
        <p className="py-8 text-center text-gray-500">{emptyLabel}</p>
      ) : (
        <div className="space-y-3">
          {groups.map((versions) => (
            <DigestGroup key={`${versions[0].period_start}_${versions[0].period_end}`} versions={versions} />
          ))}
        </div>
      )}
    </div>
  );
}
